### ISSUE TITLE
Unraid Template and Post to Community App Store

### ISSUE THREAD

**Issue by chansearrington** [relvacode/storm#33]
Hey there,

I'm not the most technical person, but I really want to use this. The Deluge UI is soo bad on the web.

Any chance you can publish this to UnRaid Community Apps, or just make an UnRaid template.

I think everyone would LOVE this in UnRaid

**Comment by plexecutor** [comment]
I second this. I am a somewhat technical person and I have been trying to get this running on Unraid with no success.

**Comment by djismgaming** [comment]
I made it possible in unRAID like this:

Prerequisites
- install binhex/delugevpn container from the Community Applications
- add an admin:password:10 to appdata\binhex-delugevpn\auth file (as shown: https://dev.deluge-torrent.org/wiki/UserGuide/Authentication)
- make sure "allow_remote": true in appdata\binhex-delugevpn\core.conf file
- install Docker Compose Manager plugin in unRAID

Then made a new stack with this compose:

```
version: '3.3'
services:
    storm:
        container_name: storm
        network_mode: linuxserver # please put here the custom network you have the deluge container on
        ports:
            - '8221:8221'
        environment:
            - DELUGE_RPC_HOSTNAME=delugevpn # deluge container name
            - DELUGE_RPC_USERNAME=admin
            - DELUGE_RPC_PASSWORD=password
            - DELUGE_RPC_VERSION=v2
        image: ghcr.io/relvacode/storm
        restart: unless-stopped
```
After this just go to the serverip:8221 and the screen will fill with all your Linux ISO torrents ;)

I may try to make my first ever unRAID template by doing it for this awesome webUI! No promises.
