### ISSUE TITLE
Failed to established Deluge PRC connection

### ISSUE THREAD

**Issue by varunpan** [relvacode/storm#41]
I am using docker and setup both deluge and storm under gluetun for vpn traffic protection. I have deluge and storm on the same docker network and both are in gluetun.

Error received:
```
2022-11-30T18:44:39.632Z	ERROR	pool	storm/pool.go:217	Failed to establish Deluge RPC connection	{"error": "dial tcp 192.168.1.4:58846: connect: connection timed out"}
2022-11-30T18:44:39.632Z	ERROR	api	storm/api.go:206	Internal Server Error	{"Method": "GET", "URL": "/api/plugins", "RemoteAddr": "192.168.1.243:57836", "Time": "2022-11-30T18:35:03.380Z", "StatusCode": 500, "ResponseSize": 103, "Duration": "9m36.252115126s", "error": "A connection to the Deluge RPC daemon could not be established by the connection pool"}
```

docker compose setup:
```
storm:
    image: ghcr.io/relvacode/storm
    container_name: storm
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_RPC_HOSTNAME=192.168.1.4
      - DELUGE_RPC_PORT=58846
      - DELUGE_RPC_USERNAME=localclient
      - DELUGE_RPC_PASSWORD=<redacted>
      - DELUGE_RPC_VERSION=v2
    # ports:
    #   - 8221:8221
    restart: unless-stopped
    networks:
      panchnet:
        ipv4_address: 172.18.5.229
```
